### PR TITLE
feat(certificates): Let the user decide whether to use or not cert-manager

### PR DESCRIPTION
**Pull request by aacecandev**
This PR moves the required ingress annotations to helpers, and let the user add more via values.yaml

### CODE REVIEW

**Review by blopezpi — APPROVED** [review]

**Comment by alpiquero** [comment]
**WARNING**: Commit [fc3cd4a](https://github.com/konstellation-io/kre/pull/572/commits/fc3cd4a9039bec6ad755d0b4d42cf41328b982c5) introduces breaking changes. See commit message for more info.

**Review by jvidal-sysadmin — COMMENTED** [review]
Looks great

**Review by jvidal-sysadmin — APPROVED** [review]

**Comment by blopezpi** [comment]
@alpiquero please create a new issue for that breaking change. And explain on it why this one introduce a break change. Because the issue is for removing cert-manager, but it's better to create another one explain the new breaking change and link it to this PR. 
Looks good!

**Review by alpiquero — APPROVED** [review]

**Comment by alpiquero** [comment]
Related issue #576

**Review by blopezpi — APPROVED** [review]

**Pull request merged**
